import { Poppins } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
import Footer from './components/Footer'
import { Toaster } from 'sonner'



const poppins = Poppins({ subsets: ['latin'], weight:['100','200','300','400','500','600','700','800'] })

export const metadata = {
  title: 'Techplusnics',
  description: 'Generated by techplusnics',
}

export default function RootLayout({ children }) {
  
  return (
    <html data-theme="light" lang="en">
      <body className={`${poppins.className} hide-scroll`}>
      <Toaster expand={true} richColors position="top-center"/>
        <Navbar/>
        {children}
        <Footer/>
    </body>
    </html>
  )
}
