<<<<<<< HEAD
import { Poppins } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'

const poppins = Poppins({ subsets: ['latin'], weight:['100','200','300','400','500','600','700','800'] })

export const metadata = {
  title: 'Techplusnics',
  description: 'Generated by techplusnics',
=======
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
>>>>>>> 9dd497c391acd36953f791d25043db4cf2d8dcdb
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body className={poppins.className}>
=======
      <body className={inter.className}>
>>>>>>> 9dd497c391acd36953f791d25043db4cf2d8dcdb
        <Navbar/>
        {children}
    </body>
    </html>
  )
}
